name: oxide-digitalsignage
version: 1
summary: Digital Signage Demo
description: Digital Signage based on Oxide WebView
confinement: devmode

apps:
    start-oxide:
        command: start-oxide
        plugs: [browser-support, opengl, network, network-bind, x11]
    chmod-vchiq:
        command: chmod-vchiq
        daemon: simple
        plugs: [ opengl ]

parts:
    oxide:
        plugin: nil
        stage-packages:
            - liboxideqt-qmlplugin
            - qmlscene
            - qt5-default
            - qtchooser
            - qtbase5-dev
            - qtdeclarative5-ubuntu-ui-toolkit-plugin
            - libraspberrypi0
            - qtdeclarative5-dev
        filesets:
            unwanted:
                - -usr/lib/arm-linux-gnueabihf/mesa-egl/
                - -usr/lib/arm-linux-gnueabihf/libGLESv2.so
                - -usr/lib/arm-linux-gnueabihf/libEGL.so
                - -usr/lib/arm-linux-gnueabihf/libQt5EglDeviceIntegration.so.5.6.1
                - -usr/lib/arm-linux-gnueabihf/qt5/plugins/platforms/libqeglfs.so
        stage:
            - $unwanted                 
        snap: 
            - $unwanted
    common:
        plugin: dump
        source: data
